# Generated by Django 3.2.8 on 2021-10-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of collected statistics')),
                ('views', models.IntegerField(default=0, verbose_name='Count of views in statistics')),
                ('clicks', models.IntegerField(default=0, verbose_name='Count of clicks in statistics')),
                ('cost', models.FloatField(default=0, verbose_name='Amount of cost of clicks in statistics')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Record adding datetime')),
            ],
            options={
                'verbose_name': 'Collected Statistics',
                'ordering': ('date', 'views', 'clicks', 'cost'),
            },
        ),
    ]
