# Generated by Django 3.2.8 on 2021-10-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Amount of cost of clicks in statistics'),
        ),
    ]
