# Generated by Django 3.2.8 on 2021-10-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_alter_statistics_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Record last updated'),
        ),
    ]
